name: 'OPA test'
description: 'Runs opa test'
inputs:
  args:
    description: |
      Argument string to pass to `opa test`.  This is currently passed to the
      shell unescaped, allowing you to pass in multiple paths or other
      arguments.
    required: true
    default: '.'
outputs: {}
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.args }}
